### ISSUE TITLE
How can I pass the default value?

### ISSUE THREAD

**Issue by webdevyriy** [Zenoo/mui-address-autocomplete#10]
When I try to remove the default value using the backspace button, I see this error

```
   <AddressSearchAutocomplete
      {...props}
      label='Address'
      value='Test'
```

![image](https://user-images.githubusercontent.com/36160567/200612918-27044a7e-b98b-4c37-bbf2-e666281a0bf4.png)
![image](https://user-images.githubusercontent.com/36160567/200612976-7643f56a-c5f5-45b3-818b-102d7d80f56e.png)

**Comment by webdevyriy** [comment]
[This is video ](https://www.awesomescreenshot.com/video/12324772?key=78cc3cbb1323e4a9a91027b614958824)

**Comment by Zenoo** [comment]
The issue probably comes from your end, I created a [demo](https://codesandbox.io/s/jolly-breeze-0sidgc?file=/src/App.js), and everything works as it should.

Simply replace the API Key by yours.

**Comment by webdevyriy** [comment]
Try this 

![image](https://user-images.githubusercontent.com/36160567/200628576-c8f9fe8a-7f5f-46e1-bf9b-21a0f45cd7ee.png)

**Comment by webdevyriy** [comment]
Same problem

**Comment by webdevyriy** [comment]
How can you save data?

**Comment by webdevyriy** [comment]
If you need to insert the data that you store?

**Comment by Zenoo** [comment]
It's up to you to save the `placeId`, and use it again later like so:
```
{
	place_id: 'tjhe placeid',
	description: 'the name'
}
```

**Comment by webdevyriy** [comment]
Could you show how it works in the sandbox?

**Comment by Zenoo** [comment]
I updated the demo with a preselected address

https://codesandbox.io/s/jolly-breeze-0sidgc?file=/src/App.js

**Comment by webdevyriy** [comment]
Thank you very much everything is working now

**Comment by webdevyriy** [comment]
If you select everything and delete it, then there is no problem, but if you delete it gradually, then it appears again

[video ](https://www.awesomescreenshot.com/video/12327503?key=f1829bc4f73b354f3b53c317194e3ebd)

**Comment by webdevyriy** [comment]
https://codesandbox.io/s/small-flower-hdhii9?file=/src/App.js

**Comment by webdevyriy** [comment]
Your option
[video](https://www.awesomescreenshot.com/video/12327957?key=7ce5170f93e78f40e3090d3206a3c88f)

**Comment by Zenoo** [comment]
I updated the sandbox, you can create a more complex object that more accurately matches the real one:

https://codesandbox.io/s/jolly-breeze-0sidgc?file=/src/App.js

```
  {
    place_id: "ChIJD7fiBh9u5kcRYJSMaMOCCwQ",
    description: "Paris, France",
    components: {},
    structured_formatting: {
      main_text: "Paris",
      secondary_text: "France",
      main_text_matched_substrings: []
    }
  }
```

**Comment by webdevyriy** [comment]
I think this can be added to the README
