### ISSUE TITLE
Plugin not working with react 18

### ISSUE THREAD

**Issue by webdevyriy** [Zenoo/mui-address-autocomplete#12]
Please update 
![image](https://user-images.githubusercontent.com/36160567/201623092-ae6b06e5-5220-4408-8e23-31f1f530af00.png)

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a CodeSandbox and send me the link?

**Comment by webdevyriy** [comment]
Yes

**Comment by webdevyriy** [comment]
> CodeSandbox

https://codesandbox.io/s/crazy-elbakyan-rt0f3b?file=/src/App.js

**Comment by Zenoo** [comment]
Thanks, I will work on releasing a React 18 compatible version

**Comment by webdevyriy** [comment]
ok

**Comment by Zenoo** [comment]
Versions 3.*.* will be React 18 compatible.

You can update to the latest (3.0.3 for now)
