### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by grenzionky** [Zenoo/mui-address-autocomplete#23]
I have a next.js typescript project with MUI, and I'm getting this error:

```
error - node_modules/mui-address-autocomplete/index.js:1
export {AddressAutocomplete} from './AddressAutocomplete';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at mui-address-autocomplete (.next/server/pages/application.js:142:18)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42) {
  page: '/'
}
```

Here's my tsconfig.json:

```json
{
	"compilerOptions": {
		"target": "es2017",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"incremental": true,
		"noUncheckedIndexedAccess": true
	},
	"ts-node": { "esm": true },
	"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.cjs", "**/*.mjs"],
	"exclude": ["node_modules"]
}
```

Not sure what the problem is. ESNext should support the export keyword just fine. it works everywhere else in my project...

**Comment by Zenoo** [comment]
Could you create a minimal project with this error on CodeSandbox?  
This is probably a misconfiguration in your project.

**Comment by grenzionky** [comment]
https://codesandbox.io/s/aectionate-jasper-7uhiih?file=/pages/index.tsx

here ya go. still getting the error

**Comment by Zenoo** [comment]
You're using an outdated version of Next, you can update it and use the module transpilation option in the config as described here: https://nextjs.org/docs/advanced-features/compiler#module-transpilation

Or use the package `next-transpile-modules`.

See https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export

**Comment by grenzionky** [comment]
it works! thanks! how did you go about finding the answer if you dont mind explaining, thanks

**Comment by Zenoo** [comment]
It's simply trial and error, and a lot of Google searching :D
