### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by nemethad** [Zenoo/mui-address-autocomplete#34]
During runtime I get this error:
Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading

**Comment by Zenoo** [comment]
Thanks for the heads up @nemethad !
This has been fixed in [v3.1.0](https://github.com/Zenoo/mui-address-autocomplete/releases/tag/v3.1.0)
