### ISSUE TITLE
v3.1.2 dist code is not the same as source code

### ISSUE THREAD

**Issue by Sylchauf** [Zenoo/mui-address-autocomplete#41]
Hello,

When i do some checks on v3.1.2 after the PR https://github.com/Zenoo/mui-address-autocomplete/pull/39 i just saw the dist code is not the same as the source code.

In fact, the correction of this PR is not present in the dist code.

See the renderAddressOption function in the file AddressAutocomplete:

- The source code contains a condition to check if matches is null
- The dist version does not contain this condition 

Could you make a new version with an updated dist code please ?

**Comment by Zenoo** [comment]
Indeed, the build was somehow outdated !
Thanks for the heads up, v3.1.3 should fix this issue.
