### ISSUE TITLE
Can you please tell me whether it is possible to manage the search in certain countries?

### ISSUE THREAD

**Issue by webdevyriy** [Zenoo/mui-address-autocomplete#8]
Hello, I really like your component. Can you please tell me whether it is possible to manage the search in certain countries?

  ```
request.componentRestrictions = { country: ['ua'] }
autocompleteService.current.getPlacePredictions(request, callback)
```

**Comment by Zenoo** [comment]
Hi @webdevyriy, did you try using the `requestOptions` prop?

**Comment by webdevyriy** [comment]
> Hi @webdevyriy, did you try using the `requestOptions` prop?

Thanks for the reply, I tried but it doesn't work

**Comment by webdevyriy** [comment]
`requestOptions='country:ua'`

**Comment by webdevyriy** [comment]
> Hi @webdevyriy, did you try using the `requestOptions` prop?

Could you give an example of how they should be used?

**Comment by Zenoo** [comment]
Try

```
requestOptions={{
	country: ['ua'],
}}
```

**Comment by webdevyriy** [comment]
> Try
> 
> ```
> requestOptions={{
> 	country: ['ua'],
> }}
> ```

Still searching in all countries

**Comment by Zenoo** [comment]
Or 

```
requestOptions={{
	componentRestrictions: {
		country: ['ua'],
	}
}}
```

**Comment by webdevyriy** [comment]
> Or
> 
> ```
> requestOptions={{
> 	componentRestrictions: {
> 		country: ['ua'],
> 	}
> }}
> ```

**It works great**

**Comment by Zenoo** [comment]
Great !  

For next time, you can check the [official Google documentation](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest.componentRestrictions) for more options.
