### ISSUE TITLE
How to replace output in input?

### ISSUE THREAD

**Issue by webdevyriy** [Zenoo/mui-address-autocomplete#9]
```
  const handleRender = (option) => {
    return typeof option === 'string' ? option : option.formatted_address
  }

 return (
    <AddressSearchAutocomplete
      value={value}
      getOptionLabel={(option) => handleRender(option) }

```

**Replacing output results in an error**

![image](https://user-images.githubusercontent.com/36160567/200383112-23197fff-800d-4644-bfea-e3292fdd5df1.png)

How can you avoid it?

**Comment by Zenoo** [comment]
There is no `formatted_address` prop in the `option` object.  

![](https://i.imgur.com/F1JiGoi.png)

![](https://i.imgur.com/tm1CBgK.png)

Also you should avoid creating useless lambdas like you are doing, simply pass the callback directly:  

```
getOptionLabel={handleRender}
```

**Comment by webdevyriy** [comment]
Please give an example of how I can change the output I work on jsx,  without typescript

**Comment by Zenoo** [comment]
It depends on what you want to display, you have all the documentation on the README

**Comment by webdevyriy** [comment]
> It depends on what you want to display, you have all the documentation on the README

Thank you for your attention
